// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DynamicFieldArray: typeof import('./components/DynamicFieldArray.vue')['default']
    FieldArea: typeof import('./components/FieldArea.vue')['default']
    FormSection: typeof import('./components/FormSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./components/SelectField.vue')['default']
    SongForm: typeof import('./components/SongForm.vue')['default']
    SongInfo: typeof import('./components/SongInfo.vue')['default']
    SongInfoDeleteConfirmation: typeof import('./components/SongInfoDeleteConfirmation.vue')['default']
    SongInfoTextSections: typeof import('./components/SongInfoTextSections.vue')['default']
    TextareaField: typeof import('./components/TextareaField.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    UserListAdd: typeof import('./components/UserListAdd.vue')['default']
    UserListItem: typeof import('./components/UserListItem.vue')['default']
  }
}
